encoding: utf-8
title:   "EmbedJournal"
host: embedjournal.com
tagline: "Add a brain to everything with embedded systems"
email:   "admin@embedjournal.com"
version: "0.2.0"
url:     "http://embedjournal.com"
baseurl: ""
logo:    "/assets/images/logo/embedjournal-120px.png"
description: > # this ignores newlines until next key.
  This is a website focusing on embedded software/hardware design and a hunch of
  other things that has to do with it. Embedded systems play a vital role in our
  day to day lives. Even without our knowledge we are using dozens of embedded
  devices.
env: production
permalink: pretty
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

disqus: embedjournal
google_analytics: UA-41190078-1

social:
  rss:         /feed.xml
  twitter:     https://twitter.com/embedjournal
  faceboook:   https://facebook.com/embedjournal
  google_plus: https://plus.google.com/+Embedjournal
  linkedin:    https://www.linkedin.com/company/3181824
  youtube:     https://www.youtube.com/user/embedjournal
  github:      https://github.com/embedjournal

collections:
  pages:
    output: true
    permalink: /:path/index.html
  authors:
    output: true
    permalink: /authors/:path/index.html
  category_pages:
    output: true
    permalink: /category/:path/index.html

liquid:
  error_mode: warn

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: "posts"   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

gems:
  - jekyll
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - octopress-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - robots.txt
  - bin

include:
  - .htaccess

jekyll-archives:
  enabled: [ "year", "month", "tags" ]
  layout: "post-list"
  permalinks:
    year:  "/archives/:year/"
    month: "/archives/:year/:month/"
    tag:   "/tag/:name/"

compress_html:
  clippings: all
  comments: all
  ignore:
    envs: development  # disable compression in dev environment
