title: "EJ Staging"
host: ""
env: developement

# Switch to local resources when working offline.
use_local_resources: true

include:
  - robots.txt

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - robots.txt
  - tools/
  - drafts/
  - .htaccess
