title:   "EmbedJournal"
host: embedjournal.com
tagline: "Add a brain to everything with embedded systems"
email:   "admin@embedjournal.com"
version: "1.0.0"
url:     "http://embedjournal.com"
encoding: utf-8
baseurl: "" # path to load the site from.
logo:    "/assets/images/logo/embedjournal-120px.png"
env: production
permalink: disqus
markdown: kramdown
use_local_resources: true # Switch to local resources when working offline.

description: > # this ignores newlines until next key.
  This is a website focusing on embedded software/hardware design and a hunch of
  other things that has to do with it. Embedded systems play a vital role in our
  day to day lives. Even without our knowledge we are using dozens of embedded
  devices.

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

google_analytics: UA-41190078-1
disqus: embedjournal

social:
  rss:         /feed.xml
  twitter:     https://twitter.com/embedjournal
  faceboook:   https://facebook.com/embedjournal
  google_plus: https://plus.google.com/+Embedjournal
  linkedin:    https://www.linkedin.com/company/3181824
  youtube:     https://www.youtube.com/user/embedjournal
  github:      https://github.com/embedjournal

collections:
  pages:
    output: true
    permalink: /:path/index.html
  authors:
    output: true
    permalink: /authors/:path/index.html
  category:
    output: true
    permalink: /category/:path/index.html

liquid:
  error_mode: warn

defaults:
  -
    scope:
      path: ""        # empty string for all files
      type: "posts"
    values:
      is_post: true
      layout: post
  -
    scope:
      path: ""       # empty string for all files
      type: "pages"
    values:
      layout: page
  -
    scope:
      path: ""       # empty string for all files
      type: "category"
    values:
      layout: category-posts

gems:
  - jekyll
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - octopress-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - robots.txt
  - tools/
  - drafts/

include:
  - .htaccess

jekyll-archives:
  enabled: [ "year", "month", "tags" ]
  layout: "post-list"
  permalinks:
    year:  "/archives/:year/"
    month: "/archives/:year/:month/"
    tag:   "/tag/:name/"

compress_html:
  clippings: all
  comments: all
  ignore:
    envs: development  # disable compression in development environment
