title: "EJ Staging"
host: ""
env: developement
disable_adsense: true

# Switch to local resources when working offline.
use_local_resources: true

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - tools/
  - drafts/
  - .htaccess
